(function(root){
function redact(text){return String(text).replace(/\b[A-HJ-NPR-Z0-9]{17}\b/gi,'[VIN REDACTED]').replace(/\b(?:VIN|Chassis\s+Number|License\s+Plate|Registration|Serial\s+(?:Number|No\.?))\s*[:=][^\r\n]*/gi,m=>m.split(/[:=]/)[0]+': [REDACTED]');}
function normalizeModule(s){return String(s||'Unassigned').replace(/\s+/g,' ').trim();}
function parse(text){const clean=redact(text);if(clean.length>5*1024*1024)throw Error('Scan exceeds the 5 MB limit.');const trimmed=clean.trim();const entries=new Map();const add=(module,code,description)=>{code=String(code).trim().toUpperCase();if(!code) return;const key=normalizeModule(module)+'|'+code;if(!entries.has(key))entries.set(key,{module:normalizeModule(module),code,description:String(description||'').trim()});};
if(trimmed.startsWith('[')||trimmed.startsWith('{')){const json=JSON.parse(trimmed);const rows=Array.isArray(json)?json:json.faults;if(!Array.isArray(rows)||rows.length>10000)throw Error('JSON must be an array of faults or {faults:[...]}.');for(const r of rows){if(!r||typeof r.code!=='string')throw Error('Each JSON fault needs a string code.');add(r.module,r.code,r.description);}return [...entries.values()];}
let module='Unassigned';for(const line of clean.split(/\r?\n/)){const header=line.match(/^\s*Address\s+([0-9A-F]{2})\s*:\s*([^\r\n]*?)(?:\s+\(|$)/i)||line.match(/^\s*\[([^\]]+)\]\s*$/);if(header){module=header.length===3?`${header[1].toUpperCase()} ${header[2].trim()}`:header[1];continue;}const numeric=line.match(/^\s*(\d{4,7})\s+-\s+(.+)$/);if(numeric){add(module,numeric[1],numeric[2]);continue;}const standard=line.match(/(?:^|\s)([PBCU][0-3][0-9A-F]{3})(?:\s|$|\s*[-:])/i);if(standard){add(module,standard[1],line.replace(standard[1],'').replace(/^\s*[-:]/,'').trim());}}return [...entries.values()];}
function diff(before,after){const key=r=>r.module+'|'+r.code;const a=new Map(before.map(r=>[key(r),r]));const b=new Map(after.map(r=>[key(r),r]));return{new:after.filter(r=>!a.has(key(r))),absent:before.filter(r=>!b.has(key(r))),persisting:after.filter(r=>a.has(key(r)))};}
const api={redact,parse,diff};if(typeof module!=='undefined')module.exports=api;else root.ScanDiff=api;
})(typeof window!=='undefined'?window:globalThis);
